name: CD

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Install .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x

      - name: Restore packages
        run: dotnet restore

      - name: Pack
        run: dotnet pack --configuration Release

      - name: Deploy
        run: dotnet nuget push DotnetRuntimeBootstrapper\bin\Release\*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}